version: '3.4'

services:
    catalogdb:
        image: mongo
    
    basketdb: 
        image: redis
    
    orderdb: 
        image: mcr.microsoft.com/mssql/server
    
    rabbitmq: 
        image: rabbitmq:3-management-alpine

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: Basket/Basket.API/Dockerfile

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: catalog/Catalog.API/Dockerfile

    ordering.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
            context: .
            dockerfile: Ordering/Ordering.API/Dockerfile

    ocelotapigateway:
        image: ${DOCKER_REGISTRY-}ocelotapigateway
        build:
            context: .
            dockerfile: APIGW/OCelotAPIGateway/Dockerfile

